name: Check versions

permissions:
  contents: write

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  check-versions:
    strategy:
      matrix:
        branch:
          - sisyphus
          - p11
          - p10
        arch:
          - amd64
    uses: alt-autorepacked/common/.github/workflows/update.yml@ff75659b10954565d4ba20dee4008f9331292c88
    with:
      branch: ${{ matrix.branch }}
      arch: ${{ matrix.arch }}
    